export {
  defaultBaseRewritePrompt,
  defaultEnglishContentPrompt,
  defaultEnglishContinuationPrompt,
  defaultEnglishMetadataPrompt,
  defaultEnglishMetadataStylePrompt,
  defaultEnglishStylePrompt,
  defaultFactExtractionPrompt,
  defaultInitialRewriteFeedbackPrompt,
  defaultMetadataPrompt,
  defaultMetadataStylePrompt,
  defaultQualityReviewPrompt,
  defaultRewriteRetryPrompt,
  resolveMetadataPromptTemplate,
  resolveSourceAnchoredRewriteTemplate,
} from "@fwqgo/core/ai-rewrite-prompts";
