import { stableNetworkExperienceChecksum } from "./checksum";
import type { NetworkExperienceRuleSetSnapshot } from "./input";

const commonVerification = ["request_test_ip_and_looking_glass", "run_ping_mtr_and_traceroute", "repeat_during_peak_hours"];
const commonRisk = ["provider_label_may_not_match_delivered_route", "return_path_may_differ"];

export const INITIAL_NETWORK_EXPERIENCE_RULES: NetworkExperienceRuleSetSnapshot["rules"] = [
  { ruleKey: "telecom-asia-carrier-optimized", networkLineSlug: "cn2-gia", networkLineName: "CN2 GIA", networkLineEnName: "CN2 GIA", userRegion: "*", carrier: "telecom", accessType: "*", destinationRegion: "*", workload: "web_api", fit: "usually_preferred", basisStrength: "common", priority: 90, conditionCodes: ["carrier_specific_access", "stable_path_is_preferred"], advantageCodes: ["carrier_optimized_route_family", "stable_path_is_preferred"], riskCodes: commonRisk, verificationCodes: commonVerification, relatedArticleIds: [6, 11] },
  { ruleKey: "telecom-asia-gt-fallback", networkLineSlug: "cn2", networkLineName: "CN2 GT", networkLineEnName: "CN2 GT", userRegion: "*", carrier: "telecom", accessType: "*", destinationRegion: "*", workload: "web_api", fit: "situational", basisStrength: "common", priority: 70, conditionCodes: ["carrier_specific_access"], advantageCodes: ["carrier_optimized_route_family"], riskCodes: [...commonRisk, "peak_hour_congestion_requires_testing"], verificationCodes: commonVerification, relatedArticleIds: [6, 11] },
  { ruleKey: "telecom-download-policy", networkLineSlug: "bgp", networkLineName: "普通 BGP", networkLineEnName: "Standard BGP", userRegion: "*", carrier: "telecom", accessType: "*", destinationRegion: "*", workload: "download", fit: "situational", basisStrength: "common", priority: 60, conditionCodes: ["download_throughput_priority"], advantageCodes: ["cdn_can_absorb_static_traffic"], riskCodes: [...commonRisk, "optimized_route_is_not_bandwidth_guarantee"], verificationCodes: [...commonVerification, "check_bandwidth_quota_and_shaping"], relatedArticleIds: [6, 11] },
  { ruleKey: "unicom-asia-cuii", networkLineSlug: "cuii", networkLineName: "CUII", networkLineEnName: "CUII", userRegion: "*", carrier: "unicom", accessType: "*", destinationRegion: "*", workload: "web_api", fit: "usually_preferred", basisStrength: "common", priority: 90, conditionCodes: ["carrier_specific_access"], advantageCodes: ["carrier_optimized_route_family", "stable_path_is_preferred"], riskCodes: commonRisk, verificationCodes: commonVerification, relatedArticleIds: [7, 11] },
  { ruleKey: "unicom-9929-fallback", networkLineSlug: "as9929", networkLineName: "AS9929", networkLineEnName: "AS9929", userRegion: "*", carrier: "unicom", accessType: "*", destinationRegion: "*", workload: "*", fit: "situational", basisStrength: "common", priority: 75, conditionCodes: ["carrier_specific_access"], advantageCodes: ["carrier_optimized_route_family"], riskCodes: [...commonRisk, "province_and_access_type_can_change_result"], verificationCodes: commonVerification, relatedArticleIds: [7, 11] },
  { ruleKey: "unicom-4837-general", networkLineSlug: "as4837", networkLineName: "AS4837", networkLineEnName: "AS4837", userRegion: "*", carrier: "unicom", accessType: "*", destinationRegion: "*", workload: "*", fit: "situational", basisStrength: "common", priority: 60, conditionCodes: ["carrier_specific_access"], advantageCodes: ["carrier_optimized_route_family"], riskCodes: [...commonRisk, "peak_hour_congestion_requires_testing"], verificationCodes: commonVerification, relatedArticleIds: [7, 11] },
  { ruleKey: "mobile-asia-cmi", networkLineSlug: "cmi", networkLineName: "CMI", networkLineEnName: "CMI", userRegion: "*", carrier: "mobile", accessType: "*", destinationRegion: "*", workload: "*", fit: "situational", basisStrength: "common", priority: 85, conditionCodes: ["carrier_specific_access"], advantageCodes: ["carrier_optimized_route_family"], riskCodes: [...commonRisk, "cross_carrier_behavior_is_not_guaranteed"], verificationCodes: [...commonVerification, "test_with_each_relevant_carrier"], relatedArticleIds: [7, 11] },
  { ruleKey: "mobile-asia-cmin2", networkLineSlug: "cmin2", networkLineName: "CMIN2", networkLineEnName: "CMIN2", userRegion: "*", carrier: "mobile", accessType: "*", destinationRegion: "*", workload: "realtime", fit: "usually_preferred", basisStrength: "limited", priority: 90, conditionCodes: ["carrier_specific_access", "realtime_sensitivity"], advantageCodes: ["carrier_optimized_route_family", "stable_path_is_preferred"], riskCodes: [...commonRisk, "cross_carrier_behavior_is_not_guaranteed"], verificationCodes: [...commonVerification, "test_with_each_relevant_carrier"], relatedArticleIds: [7, 11] },
  { ruleKey: "multi-carrier-bgp", networkLineSlug: "bgp", networkLineName: "多线 / 普通 BGP", networkLineEnName: "Multi-line / Standard BGP", userRegion: "*", carrier: "telecom", accessType: "*", destinationRegion: "*", workload: "*", fit: "situational", basisStrength: "common", priority: 50, conditionCodes: ["multi_carrier_split"], advantageCodes: ["multi_line_choice_reduces_single_carrier_dependency"], riskCodes: [...commonRisk, "cross_carrier_behavior_is_not_guaranteed"], verificationCodes: [...commonVerification, "test_with_each_relevant_carrier"], relatedArticleIds: [11] },
  { ruleKey: "multi-carrier-unicom-bgp", networkLineSlug: "bgp", networkLineName: "多线 / 普通 BGP", networkLineEnName: "Multi-line / Standard BGP", userRegion: "*", carrier: "unicom", accessType: "*", destinationRegion: "*", workload: "*", fit: "situational", basisStrength: "common", priority: 50, conditionCodes: ["multi_carrier_split"], advantageCodes: ["multi_line_choice_reduces_single_carrier_dependency"], riskCodes: [...commonRisk, "cross_carrier_behavior_is_not_guaranteed"], verificationCodes: [...commonVerification, "test_with_each_relevant_carrier"], relatedArticleIds: [11] },
  { ruleKey: "multi-carrier-mobile-bgp", networkLineSlug: "bgp", networkLineName: "多线 / 普通 BGP", networkLineEnName: "Multi-line / Standard BGP", userRegion: "*", carrier: "mobile", accessType: "*", destinationRegion: "*", workload: "*", fit: "situational", basisStrength: "common", priority: 50, conditionCodes: ["multi_carrier_split"], advantageCodes: ["multi_line_choice_reduces_single_carrier_dependency"], riskCodes: [...commonRisk, "cross_carrier_behavior_is_not_guaranteed"], verificationCodes: [...commonVerification, "test_with_each_relevant_carrier"], relatedArticleIds: [11] },
];

export const INITIAL_NETWORK_EXPERIENCE_RULE_SNAPSHOT = (() => {
  const snapshot = { versionLabel: "network-experience-v1", engineVersion: "network-experience-engine-v1", schemaVersion: 1 as const, reviewDueAt: "2027-02-01T00:00:00.000Z", rules: INITIAL_NETWORK_EXPERIENCE_RULES };
  return { ...snapshot, checksum: stableNetworkExperienceChecksum(snapshot) };
})();
