name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "18"

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connection successful"
            cd /home/ecs-user/www/fwqgo/fwqgo
            pm2 stop ecosystem.config.cjs
            find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'ecosystem.config.cjs' -exec rm -rf {} +
            git pull origin main
            echo "git pull successfiul"
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            npm install
            npm run build
            pm2 start ecosystem.config.cjs
